const mongoose = require('mongoose');
const PropertyListing = require('../models/PropertyListing');

// Connect to database
mongoose.connect('mongodb://localhost:27017/roomtopia', {
  useNewUrlParser: true,
  useUnifiedTopology: true
});

// 🎯 REALISTIC EXHIBITION PROPERTIES - MATCHES POSTPROPERTY FORM & AI FILTERS
const properties = [
  {
    title: "Cozy Single Room in Seksyen 7",
    price: 450,
    location: "Seksyen 7",
    type: "Single Room",
    description: "A comfortable single room perfect for students. Walking distance to UiTM Shah Alam. Includes bed, study table, and wardrobe. Shared kitchen and bathroom facilities.",
    contact: "012-345-6789",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "24/7 Security"],
    photos: ["https://picsum.photos/400/300?random=1", "https://picsum.photos/400/300?random=2"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Puan Siti Aminah",
    shareholderAddress: "No. 15, Jalan Seksyen 7/10, Seksyen 7, 40000 Shah Alam",
    phoneNumber: "012-345-6789",
    preferredGender: "Female Only",
    religiousPreference: "Muslim Only",
    studentYearPreference: "Any Year",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2018101000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Master Room with Private Bathroom",
    price: 650,
    location: "Seksyen 13",
    type: "Master Room",
    description: "Spacious master room with attached bathroom. Perfect for final year students who need privacy. Includes all furniture and utilities.",
    contact: "013-456-7890",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Parking", "Kitchen"],
    photos: ["https://picsum.photos/400/300?random=3", "https://picsum.photos/400/300?random=4"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Encik Ahmad Razak",
    shareholderAddress: "No. 23, Jalan Seksyen 13/8, Seksyen 13, 40100 Shah Alam",
    phoneNumber: "013-456-7890",
    preferredGender: "Male Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "Final Year Only",
    lifestylePreference: "Balanced",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Night Owl",
    userEmail: "2019019000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Shared Room for Budget Students",
    price: 300,
    location: "Seksyen 2",
    type: "Shared Room",
    description: "Affordable shared room for 2 students. Great for first-year students looking to save money. Includes basic furniture and shared facilities.",
    contact: "014-567-8901",
    amenities: ["WiFi", "Furnished", "24/7 Security"],
    photos: ["https://picsum.photos/400/300?random=5"],
    numberOfRooms: "1",
    rentalType: "Shared Space",
    furnishing: "Partially Furnished",
    parkingAvailability: "Not Available",
    shareholderName: "Puan Noraini Hassan",
    shareholderAddress: "No. 8, Jalan Seksyen 2/5, Seksyen 2, 40000 Shah Alam",
    phoneNumber: "014-567-8901",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "1st Year Only",
    lifestylePreference: "Social/Active",
    smokingPreference: "Any",
    studyHabitsPreference: "Flexible",
    userEmail: "2020378000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Modern Studio Apartment",
    price: 800,
    location: "i-City",
    type: "Studio",
    description: "Modern studio apartment with kitchenette and private bathroom. Perfect for postgraduate students or working professionals. Fully equipped with modern amenities.",
    contact: "015-678-9012",
    amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Parking", "Kitchen", "Furnished"],
    photos: ["https://picsum.photos/400/300?random=6", "https://picsum.photos/400/300?random=7", "https://picsum.photos/400/300?random=8"],
    numberOfRooms: "1",
    rentalType: "Whole Unit",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Mr. Lim Wei Ming",
    shareholderAddress: "Block A-15-08, i-City Residence, i-City, 40000 Shah Alam",
    phoneNumber: "015-678-9012",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "Any Year",
    lifestylePreference: "Balanced",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2021282000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Female-Only House in Seksyen 25",
    price: 500,
    location: "Seksyen 25",
    type: "Single Room",
    description: "Safe and secure accommodation for female students only. Located in a quiet residential area with easy access to public transport.",
    contact: "016-789-0123",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "24/7 Security", "Kitchen"],
    photos: ["/uploads/female1.jpg", "/uploads/female1_2.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Puan Fatimah Abdullah",
    shareholderAddress: "No. 12, Jalan Seksyen 25/3, Seksyen 25, 40400 Shah Alam",
    phoneNumber: "016-789-0123",
    preferredGender: "Female Only",
    religiousPreference: "Muslim Only",
    studentYearPreference: "Any Year",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2019164000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Luxury Apartment in Setia Alam",
    price: 1200,
    location: "Setia Alam",
    type: "Apartment",
    description: "Premium 2-bedroom apartment with modern facilities. Perfect for students who prefer luxury living. Includes gym, pool, and security.",
    contact: "017-890-1234",
    amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Parking", "Kitchen", "Furnished", "24/7 Security"],
    photos: ["/uploads/luxury1.jpg", "/uploads/luxury1_2.jpg", "/uploads/luxury1_3.jpg"],
    numberOfRooms: "2",
    rentalType: "Whole Unit",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Dato' Rahman Ismail",
    shareholderAddress: "Setia Sky Residences, Setia Alam, 40170 Shah Alam",
    phoneNumber: "017-890-1234",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "Final Year Only",
    lifestylePreference: "Social/Active",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2018866000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Budget Room Near Campus",
    price: 350,
    location: "Seksyen 1",
    type: "Single Room",
    description: "Very affordable single room just 5 minutes walk to UiTM main campus. Basic amenities provided. Perfect for students on tight budget.",
    contact: "018-901-2345",
    amenities: ["WiFi", "Furnished"],
    photos: ["/uploads/budget1.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Partially Furnished",
    parkingAvailability: "Not Available",
    shareholderName: "Encik Rosli Mahmud",
    shareholderAddress: "No. 5, Jalan Seksyen 1/2, Seksyen 1, 40000 Shah Alam",
    phoneNumber: "018-901-2345",
    preferredGender: "Male Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "1st Year Only",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Any",
    studyHabitsPreference: "Flexible",
    userEmail: "2022307000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Comfortable Room in Ken Rimba",
    price: 550,
    location: "Ken Rimba",
    type: "Single Room",
    description: "Well-maintained single room in a popular student area. Close to shopping centers and food courts. Includes all necessary amenities.",
    contact: "019-012-3456",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Parking", "Kitchen"],
    photos: ["/uploads/kenrimba1.jpg", "/uploads/kenrimba1_2.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Puan Zaleha Yusof",
    shareholderAddress: "No. 18, Jalan Ken Rimba 15/7, Ken Rimba, 40170 Shah Alam",
    phoneNumber: "019-012-3456",
    preferredGender: "Female Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "2nd Year Only",
    lifestylePreference: "Balanced",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Night Owl",
    userEmail: "2020575000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Spacious Room in Seksyen 6",
    price: 480,
    location: "Seksyen 6",
    type: "Single Room",
    description: "Large single room with study area and built-in wardrobe. Quiet neighborhood perfect for serious students. Near public transport.",
    contact: "012-234-5678",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "24/7 Security"],
    photos: ["/uploads/sek6_1.jpg", "/uploads/sek6_2.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Encik Hafiz Rahman",
    shareholderAddress: "No. 22, Jalan Seksyen 6/4, Seksyen 6, 40000 Shah Alam",
    phoneNumber: "012-234-5678",
    preferredGender: "Male Only",
    religiousPreference: "Muslim Only",
    studentYearPreference: "3rd Year Only",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2018173000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Modern Shared Apartment",
    price: 400,
    location: "Seksyen 8",
    type: "Shared Room",
    description: "Share a modern 3-bedroom apartment with 2 other students. Each room is private with shared common areas. Great community living.",
    contact: "013-345-6789",
    amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Parking", "Kitchen", "Furnished"],
    photos: ["/uploads/shared_apt1.jpg", "/uploads/shared_apt2.jpg"],
    numberOfRooms: "3",
    rentalType: "Shared Space",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Ms. Jennifer Tan",
    shareholderAddress: "Block B-12-05, Seksyen 8 Residences, 40000 Shah Alam",
    phoneNumber: "013-345-6789",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "2nd Year Only",
    lifestylePreference: "Social/Active",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2019794000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Cozy Studio in Kota Kemuning",
    price: 750,
    location: "Kota Kemuning",
    type: "Studio",
    description: "Beautiful studio apartment with garden view. Perfect for students who appreciate nature and tranquility. 15 minutes to campus.",
    contact: "014-456-7890",
    amenities: ["WiFi", "Air Conditioning", "Parking", "Kitchen", "Furnished"],
    photos: ["/uploads/kota_studio1.jpg", "/uploads/kota_studio2.jpg"],
    numberOfRooms: "1",
    rentalType: "Whole Unit",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Puan Mariam Osman",
    shareholderAddress: "Kota Kemuning Hills, Kota Kemuning, 40460 Shah Alam",
    phoneNumber: "014-456-7890",
    preferredGender: "Female Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "Final Year Only",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2018327000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Affordable Room in Seksyen 9",
    price: 380,
    location: "Seksyen 9",
    type: "Single Room",
    description: "Basic but clean single room for budget-conscious students. Includes essential furniture and utilities. Walking distance to local amenities.",
    contact: "015-567-8901",
    amenities: ["WiFi", "Furnished"],
    photos: ["/uploads/sek9_1.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Partially Furnished",
    parkingAvailability: "Not Available",
    shareholderName: "Encik Kamal Hashim",
    shareholderAddress: "No. 9, Jalan Seksyen 9/12, Seksyen 9, 40000 Shah Alam",
    phoneNumber: "015-567-8901",
    preferredGender: "Male Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "1st Year Only",
    lifestylePreference: "Balanced",
    smokingPreference: "Smoker Friendly",
    studyHabitsPreference: "Night Owl",
    userEmail: "2021529000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Premium Room in Seksyen 10",
    price: 600,
    location: "Seksyen 10",
    type: "Master Room",
    description: "Premium master room with ensuite bathroom and balcony. High-speed internet and premium furnishing. Perfect for serious students.",
    contact: "016-678-9012",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Parking", "Kitchen", "24/7 Security"],
    photos: ["/uploads/premium1.jpg", "/uploads/premium2.jpg", "/uploads/premium3.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Dr. Azman Sulaiman",
    shareholderAddress: "No. 45, Jalan Seksyen 10/8, Seksyen 10, 40000 Shah Alam",
    phoneNumber: "016-678-9012",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "Final Year Only",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2018988000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Female Hostel in Seksyen 24",
    price: 420,
    location: "Seksyen 24",
    type: "Single Room",
    description: "Safe female-only accommodation with 24/7 security. Includes meals and laundry service. Perfect for international students.",
    contact: "017-789-0123",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "24/7 Security", "Kitchen"],
    photos: ["/uploads/female_hostel1.jpg", "/uploads/female_hostel2.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Puan Rohani Ahmad",
    shareholderAddress: "No. 33, Jalan Seksyen 24/5, Seksyen 24, 40300 Shah Alam",
    phoneNumber: "017-789-0123",
    preferredGender: "Female Only",
    religiousPreference: "Muslim Only",
    studentYearPreference: "Any Year",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2019053000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Luxury Condo in Setia Alam",
    price: 900,
    location: "Setia Alam",
    type: "Apartment",
    description: "High-end condominium with full facilities. Swimming pool, gym, and security. Perfect for postgraduate students or working professionals.",
    contact: "018-890-1234",
    amenities: ["WiFi", "Air Conditioning", "Swimming Pool", "Parking", "Kitchen", "Furnished", "24/7 Security"],
    photos: ["/uploads/luxury_condo1.jpg", "/uploads/luxury_condo2.jpg", "/uploads/luxury_condo3.jpg"],
    numberOfRooms: "2",
    rentalType: "Whole Unit",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Mr. David Lim",
    shareholderAddress: "Setia Sky Residences, Tower B, Setia Alam, 40170 Shah Alam",
    phoneNumber: "018-890-1234",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "Final Year Only",
    lifestylePreference: "Social/Active",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2018513000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Student House in Seksyen U1",
    price: 520,
    location: "Seksyen U1",
    type: "Single Room",
    description: "Part of a student house with 4 rooms. Shared kitchen and living area. Great for making friends and study groups.",
    contact: "019-901-2345",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Parking", "Kitchen"],
    photos: ["/uploads/student_house1.jpg", "/uploads/student_house2.jpg"],
    numberOfRooms: "4",
    rentalType: "Shared Space",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Encik Razali Ibrahim",
    shareholderAddress: "No. 7, Jalan Seksyen U1/25, Seksyen U1, 40150 Shah Alam",
    phoneNumber: "019-901-2345",
    preferredGender: "Male Only",
    religiousPreference: "Any Religion",
    studentYearPreference: "2nd Year Only",
    lifestylePreference: "Social/Active",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Night Owl",
    userEmail: "2019932000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Quiet Room in Seksyen U2",
    price: 460,
    location: "Seksyen U2",
    type: "Single Room",
    description: "Peaceful single room in a quiet residential area. Perfect for students who need a calm environment for studying.",
    contact: "012-012-3456",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "24/7 Security"],
    photos: ["/uploads/quiet_room1.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Not Available",
    shareholderName: "Puan Aishah Mohd",
    shareholderAddress: "No. 14, Jalan Seksyen U2/18, Seksyen U2, 40150 Shah Alam",
    phoneNumber: "012-012-3456",
    preferredGender: "Female Only",
    religiousPreference: "Muslim Only",
    studentYearPreference: "3rd Year Only",
    lifestylePreference: "Quiet/Studious",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Early Bird",
    userEmail: "2022325000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  },
  {
    title: "Modern Room in Seksyen U16",
    price: 580,
    location: "Seksyen U16",
    type: "Single Room",
    description: "Newly renovated room with modern amenities. High-speed internet and contemporary furnishing. Close to shopping mall.",
    contact: "013-123-4567",
    amenities: ["WiFi", "Air Conditioning", "Furnished", "Parking", "Kitchen"],
    photos: ["/uploads/modern_u16_1.jpg", "/uploads/modern_u16_2.jpg"],
    numberOfRooms: "1",
    rentalType: "Room Only",
    furnishing: "Fully Furnished",
    parkingAvailability: "Available",
    shareholderName: "Encik Farid Nasir",
    shareholderAddress: "No. 28, Jalan Seksyen U16/12, Seksyen U16, 40200 Shah Alam",
    phoneNumber: "013-123-4567",
    preferredGender: "Any Gender",
    religiousPreference: "Any Religion",
    studentYearPreference: "Any Year",
    lifestylePreference: "Balanced",
    smokingPreference: "Non-Smoker Only",
    studyHabitsPreference: "Flexible",
    userEmail: "2020783000@student.uitm.edu.my",
    source: "Exhibition Demo Data",
    createdAt: new Date()
  }
];

async function seedProperties() {
  try {
    console.log('🏠 Starting property seeding...');
    
    // Clear existing demo properties
    await PropertyListing.deleteMany({ source: 'Exhibition Demo Data' });
    console.log('🗑️ Cleared existing demo properties');

    // Insert new properties
    const result = await PropertyListing.insertMany(properties);
    
    console.log(`✅ Successfully inserted ${result.length} properties!`);
    console.log('🏠 Properties distributed across:');
    console.log('   - Seksyen 1, 2, 7, 13, 25');
    console.log('   - i-City, Ken Rimba, Setia Alam');
    console.log('💰 Price range: RM 300 - RM 1200');
    console.log('🏷️ Types: Single Room, Master Room, Shared Room, Studio, Apartment');
    
    // Close connection
    await mongoose.disconnect();
    console.log('🔌 Database connection closed.');
    
  } catch (error) {
    console.error('❌ Error seeding properties:', error);
    process.exit(1);
  }
}

// Run the seeding
seedProperties();
